server_port: 8888

mysql:
  user: mysql
  password: pwd@mysql.com
  host: localhost
  port: 3306
  database: t_learn

log:
  name: log
  # trace, debug, info, warn, error, fatal
  level: debug
  time_format: 2006-01002 15:04:05.999
  # true, false
  file_number: false
jwt:
  key: habitkey